---


# Carbon

- key: iso_butyl
  query: "C[CH]([CH3])[CH3]"
- key: tertiary_butyl
  query: "C([CH3])([CH3])[CH3]"

- key: alkene
  query: "C=C"
- key: alkyne
  query: "C#C"
- key: allene
  query: "C=C=C"
- key: diene
  query: "C=CC=C"
- key: triene
  query: "C=CC=CC=C"


# Oxygen

- key: aromatic_oxygen
  query: "o"
- key: phenolic_hydroxyl
  query: "c[OH]"
- key: phenolic_hydroxyl2
  query: "[$([OH]c)]"
- key: peroxide
  query: "OO"

- key: alcohol
  query: "C[OH]"
- key: primary_alcohol
  query: "[#6][CH2][OH]"
- key: primary_alcohol2
  query: "[$([CH2][#6])][OH]"
- key: secondary_alcohol
  query: "[#6][CH]([#6])[OH]"
- key: secondary_alcohol2
  query: "[$([CH]([#6])[#6])][OH]"
- key: tertiary_alcohol
  query: "[#6][CH0]([#6])([#6])[OH]"
- key: tertiary_alcohol2
  query: "[$([CH0]([#6])([#6])[#6])][OH]"
- key: aryl_alcohol
  query: "cC[OH]"
- key: aryl_alcohol2
  query: "[$(Cc)][OH]"
- key: geminal_diol
  query: "[OH]C[OH]"

- key: ether
  query: "[#6]O[#6]"
- key: aryl_ether
  query: "cO[#6]"
- key: acetal
  query: "[#6]OCO[#6]"
- key: orthoester
  query: "[#6]OC(O[#6])O[#6]"
- key: hemiacetal
  query: "[#6]OC[OH]"

- key: carbonyl
  query: "[#6]=O"
- key: formyl
  query: "[CH]=O"
- key: acyl
  query: "O=C[#6]"
- key: acetyl
  query: "O=C[CH3]"
- key: ketone
  query: "[$(C([#6])[#6])]=O"
- key: alkyl_ketone
  query: "[$(C(C)C)]=O"
- key: aryl_Ketone
  query: "[$(C(c)[#6])]=O"
- key: ketene
  query: "C=C=O"
- key: alpha,beta-unsaturated_carbonyl
  query: "C=CC=O"

- key: carboxylate
  query: "O=CO"
- key: carboxyl
  query: "O=C[OH]"
- key: ester1
  query: "C(=O)O"
- key: ester2
  query: "[#6]C(=O)O[#6]"
- key: ester3
  query: "[$(C[#6])](=O)[$(O(C)[#6])]"
- key: ester_alip
  query: "CC(=O)OC"
- key: ester_arom
  query: "cC(=O)Oc"
- key: ester_alip_arom
  query: "CC(=O)Oc"
- key: ester_arom_alip
  query: "cC(=O)OC"
- key: lactam
  query: "[#6]C(=O)@O[#6])]"
- key: pivaloyl
  query: "OC(=O)C([CH3])([CH3])[CH3]"
- key: pivoxil
  query: "OCOC(=O)C([CH3])([CH3])[CH3]"


# Nitrogen
- key: amine
  query: "[$(N[#6])]"
- key: primary_amine
  query: "[$([NH2][#6])]"
- key: primary_amine2
  query: "[NH2][#6]"
- key: secondary_amine
  query: "[$([NH]([#6])[#6])]"
- key: secondary_amine2
  query: "[#6][NH][#6]"
- key: tertiary_amine
  query: "[$([NH0]([#6])([#6])[#6])]"
- key: tertiary_amine2
  query: "[#6][NH0]([#6])[#6]"
- key: quarternary_ammonium
  query: "[$([N+]([#6])([#6])([#6])[#6])]"
- key: quarternary_ammonium2
  query: "[#6][N+]([#6])([#6])[#6]"
- key: aromatic_nitrogen
  query: "n"
- key: aryl_amine
  query: "[$(Nc)]"
- key: aryl_amine2
  query: "Nc"

- key: imine
  query: "C=N"
- key: schiff_base
  query: "C=N-C"
- key: nitrile
  query: "C#N"
- key: cyanamide
  query: "N-C#N"
- key: hydrazine
  query: "NN"
- key: hydrazone
  query: "NN=C"
- key: hydrazide
  query: "NNC=O"
- key: azo
  query: "N=N"
- key: azide1
  query: "N=[N+]=[N-]"
- key: azide2
  query: "[N-][N+]#N"
- key: amidine
  query: "NC=N"
- key: guanidine
  query: "NC(=N)N"
- key: biguanide
  query: "NC(=N)NC(=N)N"


# O, N

- key: amide1
  query: "O=CN"
- key: amide2
  query: "[#6]C(=O)N[#6]"
- key: amide_alip
  query: "CC(=O)NC"
- key: amide_arom
  query: "cC(=O)Nc"
- key: amide_alip_arom
  query: "CC(=O)Nc"
- key: amide_arom_alip
  query: "cC(=O)NC"
- key: carbamoyl
  query: "O=C[NH2]"
- key: secondary_amide
  query: "O=C[NH][#6]"
- key: tertiary_amide
  query: "O=C[NH0]([#6])[#6]"
- key: nitro
  query: "O=[N+][O-]"
- key: nitroso
  query: "N=O"
- key: amine_oxide
  query: "[#7+][O-]"
- key: oxime
  query: "C=NO"
- key: cyanate
  query: "OC#N"
- key: isocyanate
  query: "N=C=O"
- key: carbamide
  query: "NC(=O)N"
- key: hydroxylamine
  query: "[#6][NX2][OX1]"
- key: hydroxamic acid
  query: "[#6](C=O)[NX2][OX1]"

# Sulfur

- key: sulfide
  query: "S"
- key: aromatic_sulfur
  query: "s"
- key: disulfide
  query: "SS"
- key: thiol
  query: "[#6][SH]"
- key: aryl_thiol
  query: "c[SH]"
- key: thioether
  query: "[#6]S[#6]"
- key: thiocarbonyl
  query: "C=S"
- key: thial
  query: "[CH]=S"
- key: thioketone
  query: "[#6]C(=S)[#6]"
- key: dithiocarboxylate
  query: "S=CS"


# O, N, S

- key: sulfoxide1
  query: "[#16]=O"
- key: sulfoxide2
  query: "[#16+][O-]"
- key: sulfinate
  query: "O=SO"
- key: sulfone
  query: "O=S=O"
- key: mesyl
  query: "O=S(=O)[CH3]"
- key: sulfonate
  query: "O=S(=O)O"
- key: mesylate
  query: "OS(=O)(=O)[CH3]"
- key: thioamide
  query: "S=CN"
- key: sulfoneamide
  query: "O=S(=O)N"
- key: sulfamide
  query: "NS(=O)(=O)N"
- key: thiocyanate
  query: "S-C#N"
- key: isothiocyanate
  query: "N=C=S"
- key: thiocarbamide
  query: "NC(=S)N"


# Phosphorus

- key: phosphine
  query: "P"
- key: aromatic_phosphorus
  query: "p"
- key: phosphine_oxide1
  query: "[#15]=O"
- key: phosphine_oxide2
  query: "[#15+][O-]"
- key: thiophosphinate
  query: "[O,S]=P[O,S]"
- key: phosphinate
  query: "O=PO"
- key: thiophosphonate
  query: "[O,S]=P([O,S])[O,S]"
- key: phosphonate
  query: "O=P(O)O"
- key: thiophosphate
  query: "[O,S]=P([O,S])([O,S])[O,S]"
- key: phosphate
  query: "O=P(O)(O)O"
- key: thiophosphoramidate
  query: "[O,S]=P(N)([O,S])[O,S]"
- key: phosphoramidate
  query: "O=P(N)(O)O"
- key: thiophosphordiamidate
  query: "[O,S]=P(N)(N)[O,S]"
- key: phosphordiamidate
  query: "O=P(N)(N)O"
- key: thiophosphoramide
  query: "S=P(N)(N)N"
- key: phosphoramide
  query: "O=P(N)(N)N"


# Boron

- key: borane
  query: "B"
- key: aromatic_borane
  query: "b"
- key: borinate
  query: "BO"
- key: boronate
  query: "OBO"
- key: borate
  query: "OB(O)O"


# Halogen

- key: alkylhalide
  query: "C[F,Cl,Br,I]"
- key: alkylfluoride
  query: "CF"
- key: alkylchloride
  query: "CCl"
- key: alkylbromide
  query: "CBr"
- key: alkyliodide
  query: "CI"

- key: arylhalide
  query: "c[F,Cl,Br,I]"
- key: arylfluoride
  query: "cF"
- key: arylchloride
  query: "cCl"
- key: arylbromide
  query: "cBr"
- key: aryliodide
  query: "cI"

- key: acylhalide
  query: "C(=O)[F,Cl,Br,I]"
- key: acylfluoride
  query: "C(=O)F"
- key: acylchloride
  query: "C(=O)Cl"
- key: acylbromide
  query: "C(=O)Br"
- key: acyliodide
  query: "C(=O)I"

- key: triflate
  query: "OS(=O)(=O)C(F)(F)F"
